### ISSUE TITLE
Error: Could not authenticate you.

### ISSUE THREAD

**Issue by pierrenel** [passport/express-4.x-twitter-example#1]
Bizarre - getting:

`Error: Could not authenticate you.` - I just created an app on twitter, I'll try regenerating my keys? I got exactly the same error by following another tutorial which used express/passport-twitter.

```
Error: Could not authenticate you.
   at Strategy.parseErrorResponse (/Users/pierre/Code/twitter_login/node_modules/passport-twitter/lib/strategy.js:202:14)
   at Strategy.OAuthStrategy._createOAuthError (/Users/pierre/Code/twitter_login/node_modules/passport-oauth1/lib/strategy.js:393:16)
   at /Users/pierre/Code/twitter_login/node_modules/passport-oauth1/lib/strategy.js:244:41
   at /Users/pierre/Code/twitter_login/node_modules/oauth/lib/oauth.js:543:17
   at passBackControl (/Users/pierre/Code/twitter_login/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/Users/pierre/Code/twitter_login/node_modules/oauth/lib/oauth.js:409:9)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:905:12)
   at nextTickCallbackWith2Args (node.js:478:9)
```

**Comment by pierrenel** [comment]
Nevermind, tried the code on a vps, worked perfectly 👍
