### ISSUE TITLE
Error because only essential access an not elevated access

### ISSUE THREAD

**Issue by 01231** [passport/express-4.x-twitter-example#11]
I get this Error:

`APIError: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve`

Trace:
```
    at /Users/ic/dev/express-4.x-twitter-example/node_modules/passport-twitter/lib/strategy.js:138:23
    at passBackControl (/Users/ic/dev/express-4.x-twitter-example/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/ic/dev/express-4.x-twitter-example/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

I have only essential access but I am wondering why this doesn't work. I tried the oauth-workflow with postman and it works even tough I don't have elevated access.

At which endpoint is this failing?

**Comment by 01231** [comment]
Could it be that `passport-twitter` relies on v1 of the twitter api and people with the essential access don't have access to v1?
