### ISSUE TITLE
Failed to obtain request token

### ISSUE THREAD

**Issue by shenghuowang** [passport/express-4.x-twitter-example#3]
after config key and callback,when I start server,failed to obtain request token，the log as below:
 at Strategy.OAuthStrategy._createOAuthError (/home/shenghuowangnb/express-4.x-twitter-example/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /home/shenghuowangnb/express-4.x-twitter-example/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /home/shenghuowangnb/express-4.x-twitter-example/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
    at ClientRequest.<anonymous> (/home/shenghuowangnb/express-4.x-twitter-example/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:421:9)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by nikrb** [comment]
same problem, found answer [here](https://stackoverflow.com/questions/23295662/passport-twitter-error-failed-to-find-request-token-in-session)

basically change twitter app setup url to http://127.0.0.1/login/twitter/return and in server.js ```callbackURL: 'http://localhost:3000/login/twitter/return'```

**Comment by marswong** [comment]
@shenghuowang maybe u need a global proxy to break the firewall 😃
